---
title: " "
pagetitle: "Ryan Whalen"
---
 
### Profit Maximization Model 
In collaboration with Lawrence Freight, my group and I developed a Decision Support System application in MS Excel using a Solver optimization model and VBA programming that maximizes profit based on trailer arrival rate and number of employees available to service vehicles at a given station

### Interactive Web-app for Hubbard Brook
In collaboration with research scientists at Hubbard Brook Experimental Forest, my group and I used advanced R programming to create a web-app to help researchers easily subset and analyze spatial and quantitative data obtained from experiemental watersheds. An interactive map was used to display an overview of the watershed area with optional raster layers. The interactive graphs were used to model and subset over 60 years of daily data from water table, precipitation, and discharge records collected at the Hubbard Brook Experimental Forest. 
Web-app [link](http://198.82.212.36/Map_app/) 

### Virginia Tech Food Service Vendor Accounts Payable System
In my systems development class, my group and I were tasked with developing an entire system for Virginia Tech's dining services, accounts payable office, and the check issuance office using UML diagrams. The problem involved creating a new system which optimized the process of odering and paying for dining products used by Virginia Tech dining services. The final deliverable project included an executive summary, requirements definitions, user stories, a use case diagram, activity diagrams, use case descriptions, a class diagram, sequence diagrams, a CRUDE matrix, behavioral state machines, invariants, and contracts & method specifications. The full project can be found [here](files/BIT_4524_final_project.pdf)

### Global Climate Change
This R project tested the hypothesis that recent rates of global temperature and atmospheric CO2 change is greater than pre-human rates of change. I used modern datasets such as air temperature data compiled by the Goddard Institute for Space Studies, NASA and atmospheric CO2 data compiled by Global Monitoring Laboratory of the NOAA; as well as pre-historic ice core CO2 and temperature data compiled by the Carbon Dioxide Information Analysis Center (CDIAC). I analyzed global temperature data to determine if Earth's average global temperatures are increasing and CO2 data to determine if atmospheric levels are increasing; correlated the atmospheric CO2 data with global temperature to determine if there's a relationship; and compared the current trends with rates of change during pre-historic periods.

### Movie Theater Database 
In my database technology class, my partner and I designed and developed a functioning relational database using MySQL and phpMyAdmin for a movie theater that managed the sales, inventory, and personal data for employees and customers. The final deliveable project was a MySQL database that contained  stored procedures, triggers to respond to changes in their "home" table by automatically updating values in a seperate related table, and various tables containing fictious sales, inventory, movie, customer and employee data. The database can be found [here](files/BIT_4514_final_project.pdf)

### Land Cover/Land Use Change (LULCC) from Flooding
In my information technology class, I used ArcGIS Pro to analyze the effects of a flood and calculate the differences in land use/land cover (LULC) in a region of Mississippi captured by two Landsat TM images before and after the flood occured. I used classification algorithms and overlay analysis to analyze and determine the changes in land cover due to the flood. [Results](files/lulc_project.pdf)